pipeline {
    agent any

    tools{
        maven 'maven 3.6.1'
    }
    stages{
        stage('build'){
            steps{
                echo 'compiling worker app'
                dir('worker'){
                 sh 'maven compile'   
                }
            }

        }
        stage('test'){
            steps{
                echo "Running unit Test on worker app"
            }
        }
        stage('package'){
            steps{
                echo 'packaging worker app'
            }
        }
    }
    post{
        always{
            echo 'Building Multibranch pipeline for worker app is completed'
        }
    }
}
